language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t amanovishnu/docker-react:latest -f Dockerfile.dev .

script:
  - docker run -e CI=true amanovishnu/docker-react:latest npm run test